apiVersion: jamiethompson.me/v1alpha1
kind: PredictiveHorizontalPodAutoscaler
metadata:
  name: upf-predictive-scaler
  namespace: nexslice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oai-upf # <--- Assure-toi que c'est le bon nom !
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  models:
  - type: Linear
    name: simple-linear
    linear:
      lookAhead: 10000
      historySize: 6
